version: "3.9"
   
volumes:
  static:

services:
  db:
    ports:
      - "5000:5432"
    image: postgres:12
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=restaurant_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=resto
  web:
    restart: always
    build: .
    volumes:
      - "static:/static"
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    restart: always
    image: nginx:stable
    ports:
        - "80:80"
        - "443:443"
    volumes:
      - "static:/static"
      - ./nginx/sites-enabled/storecard.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web